exclude = [".venv"]
fix = true
line-length = 100
[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true
# Format all docstring code snippets with a line length of 100.
docstring-code-line-length = 100

